export const personaDescriptions = {
    PersonaTitle: "A descriptive title of this persona",
    PersonaSummary: "A brief summary of the persona's key details.",
    Metadata: "Metadata about the persona, including content warnings.",
    ContentWarnings: "Specific warnings about sensitive or triggering content associated with the persona, helping to ensure safe and informed interactions.",
    PresentationAndResultingBehavior: "Describes how the persona presents and behaves.",
    Affect: "Details the persona's emotional state or mood.",
    Speech: "Details how the persona communicates verbally.",
    Misc: "Additional behaviors or characteristics not covered elsewhere.",
    Identity: "Information about the persona's identity attributes.",
    Name: "The persona's name.",
    Age: "The persona's age.",
    Ethnicity: "The persona's ethnicity.",
    Sex: "Sex assigned at birth.",
    Gender: "The persona's gender identity.",
    SexualOrientation: "The persona's sexual orientation.",
    HealthComponents: "Details about the persona's health.",
    ChiefComplaint: "The main reason the persona is seeking care.",
    Diagnosis: "Information about the persona's diagnoses.",
    Differential: "Possible diagnoses being considered.",
    Actual: "The confirmed diagnosis.",
    HistoryOfPresentIllness: "Details of the persona's current health issue.",
    MedicationsAndAllergies: "The persona's medications and allergies.",
    PastMedicalHistory: "The persona's past medical history.",
    FamilyMedicalHistory: "The persona's family medical history.",
    PsychiatricProfile: "The persona's psychiatric history or profile.",
    Goals: "The goals or objectives of the persona.",
    Challenges: "The challenges faced by the persona.",
    ThoughtsAndFeelings: "The persona's thoughts and feelings.",
    TasksAndActivities: "Tasks or activities relevant to the persona.",
    InfluencesAndSupports: "The persona's social supports and influences.",
    SocialHistory: "The persona's social history.",
    CulturalComponents: "Cultural aspects relevant to the persona.",
    EmotionalWellbeing: "Details about the persona's emotional wellbeing.",
    SocialDeterminantsOfHealth: "Factors impacting the persona's health from a social perspective.",
    PromptsAndSpecialInstructions: "Special instructions or prompts related to the persona."
  };
  